import pytest
from anki_card_object import Anki_Card



@pytest.fixture
def cards_variations() -> list[Anki_Card]:
    return [
        Anki_Card(
            42,
            2,
            ["BIR::2021", "BIR::Fisiologia_Histologia", "OFICIALES::60%-70%"],
            "16. Pregunta 16<br><br><br>    1=> Opcion 1<br><br>    2=> Opcion 2<br><br>    3=> Opcion 3<br><br>    4=> Opcion 4",
            "1",
            [
                {"ease": 1, "lastIvl": 0},
                {"ease": 3, "lastIvl": 100},
                {"ease": 2, "lastIvl": 100},
                {"ease": 2, "lastIvl": 100},
                {"ease": 2, "lastIvl": 100},
            ],
        ),
        Anki_Card(
            65,
            4,
            ["BIR::2021", "BIR::Fisiologia_Histologia", "OFICIALES::70%-80%"],
            "16. Pregunta 16<br><br><br>    1=> Opcion 1<br><br>    2=> Opcion 2<br><br>    3=> Opcion 3<br><br>    4=> Opcion 4",
            "1",
            [
                {"ease": 3, "lastIvl": 0},
                {"ease": 1, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 2, "lastIvl": 100},
            ],
        ),
        Anki_Card(
            74,
            6,
            ["BIR::2021", "BIR::Fisiologia_Histologia", "OFICIALES::80%-90%"],
            "16. Pregunta 16<br><br><br>    1=> Opcion 1<br><br>    2=> Opcion 2<br><br>    3=> Opcion 3<br><br>    4=> Opcion 4",
            "1",
            [
                {"ease": 1, "lastIvl": 0},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 2, "lastIvl": 100},
            ],
        ),
        Anki_Card(
            84,
            8,
            ["BIR::2021", "BIR::Fisiologia_Histologia", "OFICIALES::90%-99%"],
            "16. Pregunta 16<br><br><br>    1=> Opcion 1<br><br>    2=> Opcion 2<br><br>    3=> Opcion 3<br><br>    4=> Opcion 4",
            "1",
            [
                {"ease": 3, "lastIvl": 0},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 2, "lastIvl": 100},
            ],
        ),
        Anki_Card(
            92,
            8,
            ["BIR::2021", "BIR::Fisiologia_Histologia", "OFICIALES::100%"],
            "16. Pregunta 16<br><br><br>    1=> Opcion 1<br><br>    2=> Opcion 2<br><br>    3=> Opcion 3<br><br>    4=> Opcion 4",
            "1",
            [
                {"ease": 1, "lastIvl": 0},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
            ],
        ),
        Anki_Card(
            100,
            8,
            ["BIR::2021", "BIR::Fisiologia_Histologia", "OFICIALES::100%"],
            "16. Pregunta 16<br><br><br>    1=> Opcion 1<br><br>    2=> Opcion 2<br><br>    3=> Opcion 3<br><br>    4=> Opcion 4",
            "1",
            [
                {"ease": 3, "lastIvl": 0},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
            ],
        ),
        Anki_Card(
            1001,
            8,
            [
                "BIR::2021",
                "BIR::Fisiologia_Histologia",
                "OFICIALES::100%",
                "OFICIALES::MODED",
            ],
            "16. Pregunta 16<br><br><br>    1=> Opcion 1<br><br>    2=> Opcion 2<br><br>    3=> Opcion 3<br><br>    4=> Opcion 4",
            "1",
            [
                {"ease": 3, "lastIvl": 0},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
            ],
        ),
        Anki_Card(
            1,
            1,
            ["BIR::2021", "BIR::Fisiologia_Histologia", "OFICIALES::70-80%", "GOBIR"],
            "GOBIR image-oclusion",
            "GOBIR image-oclusion",
            [
                {"ease": 1, "lastIvl": 0},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 2, "lastIvl": 100},
            ],
        ),
        Anki_Card(
            15,
            15,
            [
                "BIR::2021",
                "BIR::Fisiologia_Histologia",
                "OFICIALES::100%",
                "OFICIALES::MODED",
            ],
            "16. Pregunta 16<br><br><br>    1=> Opcion 1<br><br>    2=> Opcion 2<br><br>    3=> Opcion 3<br><br>    4=> Opcion 4",
            "1",
            [
                {"ease": 1, "lastIvl": 0},
                {"ease": 1, "lastIvl": 100},
                {"ease": 1, "lastIvl": 100},
                {"ease": 1, "lastIvl": 100},
                {"ease": 1, "lastIvl": 100},
                {"ease": 1, "lastIvl": 100},
                {"ease": 1, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
                {"ease": 3, "lastIvl": 100},
            ],
        ),
    ]
